version: "3"
volumes:
  data:
services:
  front:
    build: ./frontend/
    volumes:
      - ./frontend:/app
    ports:
      - 5000:5173
    links:
      - api-service
    depends_on:
      - api-service
  api-service:
    build: .
    volumes:
      - ./:/app
    ports:
      - 4000:80
      - 444:443
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8002:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: proyecto_ds
      MYSQL_USER: proyecto_ds
      MYSQL_PASSWORD: proyecto_ds
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3326:3306
